### ISSUE TITLE
User Stories and Acceptance Criteria

### ISSUE THREAD

**Issue by AustinBQ02** [SeanAllen19/GIT-IDEAS#10]
## User Story

> AS A developer in need of project ideas
> I WANT an app that will search GitHub and return results
> SO THAT I can save good ideas for future development with comments

## Acceptance Criteria

> GIVEN a super duper search and save site

WHEN I visit the site for the first time
THEN I am presented with the homepage (search), which includes a short description and search input boxes; navigation links for the homepage and the dashboard; and the option to log in

WHEN I click on the homepage option
THEN I am taken to the homepage

WHEN I click on any other links in the navigation
THEN I am prompted to either sign up or sign in

WHEN I choose to sign up
THEN I am prompted to sign in with my GitHub account

WHEN I sign-up with GitHub
THEN my user credentials are saved and I am logged into the site

WHEN I revisit the site at a later time and choose to sign in
THEN I am prompted to sign in with GitHub

WHEN I am signed in to the site
THEN I see navigation links for the homepage (search), the dashboard, and the option to log out

WHEN I click on the homepage option in the navigation
THEN I am taken to the homepage and presented text fields that allow the input of search terms

WHEN I input search terms and click "Search"
THEN I am presented with a list of results from GitHub that meet my criteria

WHEN I enter a comment for a result and click on the save button while signed in
THEN the comment and the GitHub result are saved and the page updates to indicate as such

WHEN I click on the dashboard option in the navigation
THEN I am taken to the dashboard and presented with any results I have already saved and the option to update or remove them

WHEN I click on the button to update a saved result
THEN I am prompted to change the existing comment or link and the page updates when I click save

WHEN I click on the button to create a new entry
THEN I am prompted for a link and comments and I am taken back to an updated dashboard with my new entry

WHEN I click on the logout option in the navigation
THEN I am signed out of the site

WHEN I am idle on the site for more than a set time
THEN I am able to view results but I am prompted to log in again before I can add, update, or delete anything

**Comment by brettnachman** [comment]
User Story
AS A bootcamp student in need of project/portfolio ideas
 I WANT an app that will search GitHub and return results based on my keywords 
SO THAT I can save and annotate project ideas for future work

Acceptance Criteria
GIVEN a website that allows for curation and annotation of projects from GitHub

WHEN I visit the site for the first time
 THEN I am presented with the homepage, which includes a short description and search input box, along with a button leading me to a log in/sign up page.

WHEN I click the login button
THEN I am taken to a page that allows me to login or sign up

WHEN I sign up successfully
THEN I am automatically logged in and taken to my previous page

WHEN I login successfully
THEN I am taken to my personal account page

WHEN I am logged in
THEN I will see an option to log out

WHEN I click search with no keywords submitted
THEN I get back a list of results based on a relevant, hardcoded keyword

WHEN I search for keywords in the search box
THEN I am presented with a list of results based on my search. 

WHEN I scroll through my search results
THEN I will see information such as the project title, description, measure of popularity, etc., and a link to the actual repository on GitHub.

WHEN I click on the GitHub repository link
THEN I will see a new tab opened to the relevant GitHub webpage

WHEN I click on the project title
THEN I am taken to a page that allows me to annotate with comments and tags

WHEN I am on the project annotation page
THEN I am given the option to write comments and create/append tags

WHEN I am done with comments and tags
THEN I have the ability to save the project with my annotations or go back to the results

WHEN I click Save without logging in
THEN I am taken to a login or signup page

WHEN I click Save as a logged-in user
THEN The project/annotations is saved to my personal account

WHEN I have successfully saved a project to my account
THEN The website notifies me of this

WHEN I have successfully saved a project to my account
THEN The website returns to the search results page

WHEN I am on my personal account page
THEN I can see a list of all of my saved projects and annotations

WHEN I am on my personal account page
THEN I will see the options to edit and delete my saved projects/annotations

WHEN I click the homepage button
THEN I am taken to the homepage with search box and login or logout button

WHEN I click the Logout button
THEN I am logged out of the site
